version: "3.8"

services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nila-app-nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - client
  #     - api
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

  client:
    build: ./client
    container_name: nila-app-client
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nila-app-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: >
      sh -c "
        echo '🔁 Waiting for DB...' &&
        sleep 5 &&
        bunx drizzle-kit generate &&
        bunx drizzle-kit migrate &&
        bun run start:dev
      "
    depends_on:
      - db
    volumes:
      - ./api:/app

  db:
    image: postgres:15-alpine
    container_name: nila-app-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
