version: "3.8"

services:
  #  client:
  #  build:
  #    context: ./client
  #    dockerfile: Dockerfile
  #  container_name: react-client
  #  ports:
  #    - "3001:3000"
  #  depends_on:
  #    - api
  #  volumes:
  #    - ./client:/app
  #  command: bun --hot src/index.tsx
  client:
    build: ./client
    container_name: nila-app-frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nila-app-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_TYPE=postgres
    command: >
      sh -c "
        echo '🔁 Waiting for DB...' &&
        sleep 5 &&
        bun run migration:run &&
        bun run start:dev
      "
    depends_on:
      - db
    volumes:
      - ./api:/app

  db:
    image: postgres:15-alpine
    container_name: nila-app-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
